-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 11:29:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `Cod_Proveedor` INT NOT NULL,
  `descripción` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL NULL,
  PRIMARY KEY (`Cod_Proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `cod_repuesto` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `Existencia` VARCHAR(45) NOT NULL,
  `Cod_Proveedor` VARCHAR(45) NOT NULL,
  `Pedido_nro_de_pedido` INT NOT NULL,
  PRIMARY KEY (`cod_repuesto`),
  INDEX `fk_Inventario_Proveedores_idx` (`Cod_Proveedor` ASC) VISIBLE,
  INDEX `fk_Inventario_Pedido1_idx` (`Pedido_nro_de_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Proveedores`
    FOREIGN KEY (`Cod_Proveedor`)
    REFERENCES `mydb`.`Proveedores` (`Cod_Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Pedido1`
    FOREIGN KEY (`Pedido_nro_de_pedido`)
    REFERENCES `mydb`.`Pedido` (`nro_de_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `nro_de_pedido` INT NOT NULL,
  `nro_de_orden` INT NOT NULL,
  `cantidad` INT NULL,
  `subtotal` INT NULL,
  `cod_repuesto` INT NOT NULL,
  PRIMARY KEY (`nro_de_pedido`),
  INDEX ` cod_repuesto_idx` (`cod_repuesto` ASC) VISIBLE,
  CONSTRAINT ` cod_repuesto`
    FOREIGN KEY (`cod_repuesto`)
    REFERENCES `mydb`.`Inventario` (`cod_repuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
