-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 16:45:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedores` (
  `Cod_Proveedor` INT NOT NULL,
  `descripción` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL NULL,
  PRIMARY KEY (`Cod_Proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `cod_repuesto` INT NOT NULL,
  `Cod_Proveedor` VARCHAR(45) NOT NULL,
  `Pedido_nro_de_pedido` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `Existencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_repuesto`),
  INDEX `fk_Inventario_Proveedores_idx` (`Cod_Proveedor` ASC) VISIBLE,
  INDEX `fk_Inventario_Pedido1_idx` (`Pedido_nro_de_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Proveedores`
    FOREIGN KEY (`Cod_Proveedor`)
    REFERENCES `mydb`.`Proveedores` (`Cod_Proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Pedido1`
    FOREIGN KEY (`Pedido_nro_de_pedido`)
    REFERENCES `mydb`.`Pedido` (`nro_de_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Teléfono` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehículo` (
  `Patente` VARCHAR(10) NOT NULL,
  `ID_cliente` INT NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Patente`),
  INDEX `fk_Vehiculo_Cliente_idx_idx` (`ID_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_Cliente_idx`
    FOREIGN KEY (`ID_cliente`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orden_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orden_de_trabajo` (
  `Nro_de_orden` INT NOT NULL,
  `Patente` VARCHAR(10) NOT NULL,
  `Desripcion` VARCHAR(45) NULL,
  `Fecha_ingreso` DATE NOT NULL,
  `Fecha_egreso` DATE NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nro_de_orden`),
  INDEX `fk_Orden_de_trabajo_Vehículo1_idx` (`Patente` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_de_trabajo_Vehículo1`
    FOREIGN KEY (`Patente`)
    REFERENCES `mydb`.`Vehículo` (`Patente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `nro_de_pedido` INT NOT NULL,
  `cod_repuesto` INT NOT NULL,
  `Nro_de_orden` INT NOT NULL,
  `cantidad` INT NULL,
  `subtotal` INT NULL,
  PRIMARY KEY (`nro_de_pedido`),
  INDEX ` cod_repuesto_idx` (`cod_repuesto` ASC) VISIBLE,
  INDEX `fk_Pedido_Orden_de_trabajo1_idx` (`Nro_de_orden` ASC) VISIBLE,
  CONSTRAINT ` cod_repuesto`
    FOREIGN KEY (`cod_repuesto`)
    REFERENCES `mydb`.`Inventario` (`cod_repuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Orden_de_trabajo1`
    FOREIGN KEY (`Nro_de_orden`)
    REFERENCES `mydb`.`Orden_de_trabajo` (`Nro_de_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `Nro_de_factura` INT NOT NULL,
  `Nro_de_pedido` INT NOT NULL,
  `ID_cliente` INT NOT NULL,
  `Fecha_emisión` DATETIME NOT NULL,
  `Tipo_de_factura` CHAR NULL,
  `Precio_repuesto` DECIMAL(12,2) NOT NULL,
  `Mano_de_obra` DECIMAL(12,2) NOT NULL,
  `Subtotal` DECIMAL(12,2) NOT NULL,
  `IVA` DECIMAL(12,2) NOT NULL,
  `Total` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`Nro_de_factura`),
  INDEX `fk_Factura_Pedido_idx_idx` (`Nro_de_pedido` ASC) VISIBLE,
  INDEX `fk_Factura_Cliente_idx_idx` (`ID_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Pedido_idx`
    FOREIGN KEY (`Nro_de_pedido`)
    REFERENCES `mydb`.`Pedido` (`nro_de_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Cliente_idx`
    FOREIGN KEY (`ID_cliente`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `Cod_mecanico` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_mecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MecanicoOrden_de_trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MecanicoOrden_de_trabajo` (
  `ID` INT NOT NULL,
  `Orden_de_trabajo_Nro_de_orden` INT NOT NULL,
  `Mecanico_Cod_mecanico` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Orden_de_trabajo_idx` (`Orden_de_trabajo_Nro_de_orden` ASC) VISIBLE,
  INDEX `fk_Mecanico_idx` (`Mecanico_Cod_mecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_de_trabajo`
    FOREIGN KEY (`Orden_de_trabajo_Nro_de_orden`)
    REFERENCES `mydb`.`Orden_de_trabajo` (`Nro_de_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico`
    FOREIGN KEY (`Mecanico_Cod_mecanico`)
    REFERENCES `mydb`.`Mecanico` (`Cod_mecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
